### ISSUE TITLE
if the adapter is null. the listView may crash in when pulling down

### ISSUE THREAD

**Issue by dangtao** [woozzu/RefreshableListView#2]
First thank you for sharing such a nice listview  ^^
I add a try-catch block in public boolean dispatchTouchEvent(MotionEvent ev) and catch the exception NULL-EXCEPTION.

**Comment by woozzu** [comment]
This bug is fixed now:)

**Comment by dangtao** [comment]
thanks for reply

I will try later

**Comment by dangtao** [comment]
I am sorry to find that the bug is still there.
I will try to figure it out when not that busy.
Thanks for your effort!
